// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Used for advanced voice options.
public struct AdvancedVoiceOptions: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Only for Journey voices. If false, the synthesis is context aware
  /// and has a higher latency.
  public var lowLatencyJourneySynthesis: Swift.Bool? = nil

  /// Optional. Input only. Deprecated, use safety_settings instead.
  /// If true, relaxes safety filters for Gemini TTS.
  @available(*, deprecated)
  public var relaxSafetyFilters: Swift.Bool = Swift.Bool()

  /// Optional. Input only. This applies to Gemini TTS only. If set, the category
  /// specified in the safety setting will be blocked if the harm probability is
  /// above the threshold. Otherwise, the safety filter will be disabled by
  /// default.
  public var safetySettings: AdvancedVoiceOptions.SafetySettings? = nil

  /// Optional. If true, textnorm will be applied to text input. This feature is
  /// enabled by default. Only applies for Gemini TTS.
  public var enableTextnorm: Swift.Bool? = nil

  /// Initialize a new instance of `AdvancedVoiceOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdvancedVoiceOptions().with { $0.lowLatencyJourneySynthesis = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Safety setting for a single harm category.
  public struct SafetySetting: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The harm category to apply the safety setting to.
    public var category: AdvancedVoiceOptions.HarmCategory = AdvancedVoiceOptions.HarmCategory()

    /// The harm block threshold for the safety setting.
    public var threshold: AdvancedVoiceOptions.HarmBlockThreshold =
      AdvancedVoiceOptions.HarmBlockThreshold()

    /// Initialize a new instance of `SafetySetting`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SafetySetting().with { $0.category = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.texttospeech.v1.AdvancedVoiceOptions.SafetySetting"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Safety settings for the request.
  public struct SafetySettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The safety settings for the request.
    public var settings: [AdvancedVoiceOptions.SafetySetting] = []

    /// Initialize a new instance of `SafetySettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SafetySettings().with { $0.settings = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.texttospeech.v1.AdvancedVoiceOptions.SafetySettings"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Harm categories that will block the content.
  public enum HarmCategory: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Content that promotes violence or incites hatred against individuals or
    /// groups based on certain attributes.
    case hateSpeech
    /// Content that promotes, facilitates, or enables dangerous activities.
    case dangerousContent
    /// Abusive, threatening, or content intended to bully, torment, or ridicule.
    case harassment
    /// Content that contains sexually explicit material.
    case sexuallyExplicit
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .hateSpeech: return 1
      case .dangerousContent: return 2
      case .harassment: return 3
      case .sexuallyExplicit: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HARM_CATEGORY_UNSPECIFIED"
      case .hateSpeech: return "HARM_CATEGORY_HATE_SPEECH"
      case .dangerousContent: return "HARM_CATEGORY_DANGEROUS_CONTENT"
      case .harassment: return "HARM_CATEGORY_HARASSMENT"
      case .sexuallyExplicit: return "HARM_CATEGORY_SEXUALLY_EXPLICIT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HarmCategory/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HARM_CATEGORY_UNSPECIFIED": self = .unspecified
      case "HARM_CATEGORY_HATE_SPEECH": self = .hateSpeech
      case "HARM_CATEGORY_DANGEROUS_CONTENT": self = .dangerousContent
      case "HARM_CATEGORY_HARASSMENT": self = .harassment
      case "HARM_CATEGORY_SEXUALLY_EXPLICIT": self = .sexuallyExplicit
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HarmCategory/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .hateSpeech
      case 2: self = .dangerousContent
      case 3: self = .harassment
      case 4: self = .sexuallyExplicit
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .hateSpeech: return try container.encode(1)
      case .dangerousContent: return try container.encode(2)
      case .harassment: return try container.encode(3)
      case .sexuallyExplicit: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Harm block thresholds for the safety settings.
  public enum HarmBlockThreshold: Codable, Equatable, Sendable {
    /// The harm block threshold is unspecified.
    case unspecified
    /// Block content with a low harm probability or higher.
    case blockLowAndAbove
    /// Block content with a medium harm probability or higher.
    case blockMediumAndAbove
    /// Block content with a high harm probability.
    case blockOnlyHigh
    /// Do not block any content, regardless of its harm probability.
    case blockNone
    /// Turn off the safety filter entirely.
    case off
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .blockLowAndAbove: return 1
      case .blockMediumAndAbove: return 2
      case .blockOnlyHigh: return 3
      case .blockNone: return 4
      case .off: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "HARM_BLOCK_THRESHOLD_UNSPECIFIED"
      case .blockLowAndAbove: return "BLOCK_LOW_AND_ABOVE"
      case .blockMediumAndAbove: return "BLOCK_MEDIUM_AND_ABOVE"
      case .blockOnlyHigh: return "BLOCK_ONLY_HIGH"
      case .blockNone: return "BLOCK_NONE"
      case .off: return "OFF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:HarmBlockThreshold/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "HARM_BLOCK_THRESHOLD_UNSPECIFIED": self = .unspecified
      case "BLOCK_LOW_AND_ABOVE": self = .blockLowAndAbove
      case "BLOCK_MEDIUM_AND_ABOVE": self = .blockMediumAndAbove
      case "BLOCK_ONLY_HIGH": self = .blockOnlyHigh
      case "BLOCK_NONE": self = .blockNone
      case "OFF": self = .off
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:HarmBlockThreshold/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .blockLowAndAbove
      case 2: self = .blockMediumAndAbove
      case 3: self = .blockOnlyHigh
      case 4: self = .blockNone
      case 5: self = .off
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .blockLowAndAbove: return try container.encode(1)
      case .blockMediumAndAbove: return try container.encode(2)
      case .blockOnlyHigh: return try container.encode(3)
      case .blockNone: return try container.encode(4)
      case .off: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.AdvancedVoiceOptions"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
