// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Pronunciation customization for a phrase.
public struct CustomPronunciationParams: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The phrase to which the customization is applied.
  /// The phrase can be multiple words, such as proper nouns, but shouldn't span
  /// the length of the sentence.
  public var phrase: Swift.String? = nil

  /// The phonetic encoding of the phrase.
  public var phoneticEncoding: CustomPronunciationParams.PhoneticEncoding? = nil

  /// The pronunciation of the phrase. This must be in the phonetic encoding
  /// specified above.
  public var pronunciation: Swift.String? = nil

  /// Initialize a new instance of `CustomPronunciationParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomPronunciationParams().with { $0.phrase = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The phonetic encoding of the phrase.
  public enum PhoneticEncoding: Codable, Equatable, Sendable {
    /// Not specified.
    case unspecified
    /// IPA, such as apple -> ˈæpəl.
    /// https://en.wikipedia.org/wiki/International_Phonetic_Alphabet
    case ipa
    /// X-SAMPA, such as apple -> "{p@l".
    /// https://en.wikipedia.org/wiki/X-SAMPA
    case xSampa
    /// For reading-to-pron conversion to work well, the `pronunciation` field
    ///  should only contain Kanji, Hiragana, and Katakana.
    ///
    /// The pronunciation can also contain pitch accents.
    /// The start of a pitch phrase is specified with `^` and the down-pitch
    /// position is specified with `!`, for example:
    ///
    ///     phrase:端  pronunciation:^はし
    ///     phrase:箸  pronunciation:^は!し
    ///     phrase:橋  pronunciation:^はし!
    ///
    /// We currently only support the Tokyo dialect, which allows at most one
    /// down-pitch per phrase (i.e. at most one `!` between `^`).
    case japaneseYomigana
    /// Used to specify pronunciations for Mandarin words. See
    /// https://en.wikipedia.org/wiki/Pinyin.
    ///
    /// For example: 朝阳, the pronunciation is "chao2 yang2". The number
    /// represents the tone, and there is a space between syllables. Neutral
    /// tones are represented by 5, for example 孩子 "hai2 zi5".
    case pinyin
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ipa: return 1
      case .xSampa: return 2
      case .japaneseYomigana: return 3
      case .pinyin: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PHONETIC_ENCODING_UNSPECIFIED"
      case .ipa: return "PHONETIC_ENCODING_IPA"
      case .xSampa: return "PHONETIC_ENCODING_X_SAMPA"
      case .japaneseYomigana: return "PHONETIC_ENCODING_JAPANESE_YOMIGANA"
      case .pinyin: return "PHONETIC_ENCODING_PINYIN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PHONETIC_ENCODING_UNSPECIFIED": self = .unspecified
      case "PHONETIC_ENCODING_IPA": self = .ipa
      case "PHONETIC_ENCODING_X_SAMPA": self = .xSampa
      case "PHONETIC_ENCODING_JAPANESE_YOMIGANA": self = .japaneseYomigana
      case "PHONETIC_ENCODING_PINYIN": self = .pinyin
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ipa
      case 2: self = .xSampa
      case 3: self = .japaneseYomigana
      case 4: self = .pinyin
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ipa: return try container.encode(1)
      case .xSampa: return try container.encode(2)
      case .japaneseYomigana: return try container.encode(3)
      case .pinyin: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.CustomPronunciationParams"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
