// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the `StreamingSynthesize` method. Multiple
/// `StreamingSynthesizeRequest` messages are sent in one call.
/// The first message must contain a `streaming_config` that
/// fully specifies the request configuration and must not contain `input`. All
/// subsequent messages must only have `input` set.
public struct StreamingSynthesizeRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The request to be sent, either a StreamingSynthesizeConfig or
  /// StreamingSynthesisInput.
  public var streamingRequest: OneOf_StreamingRequest? = nil

  /// Initialize a new instance of `StreamingSynthesizeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamingSynthesizeRequest().with { $0.streamingConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case streamingConfig = "streamingConfig"
    case input = "input"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var streamingRequest: OneOf_StreamingRequest? = nil
    let streamingRequestCheckAndSet = {
      if streamingRequest != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'streamingRequest'"))
      }
      streamingRequest = $0
    }
    if let streamingConfig = try container.decodeIfPresent(
      StreamingSynthesizeConfig?.self, forKey: .streamingConfig)
    {
      try streamingRequestCheckAndSet(.streamingConfig(streamingConfig))
    }
    if let input = try container.decodeIfPresent(StreamingSynthesisInput?.self, forKey: .input) {
      try streamingRequestCheckAndSet(.input(input))
    }
    self.streamingRequest = streamingRequest
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.streamingRequest {
      switch choice {
      case .streamingConfig(let value):
        try container.encode(value, forKey: .streamingConfig)
      case .input(let value):
        try container.encode(value, forKey: .input)
      }
    }
  }

  /// The request to be sent, either a StreamingSynthesizeConfig or
  /// StreamingSynthesisInput.
  public enum OneOf_StreamingRequest: Codable, Equatable, Sendable {
    /// StreamingSynthesizeConfig to be used in this streaming attempt. Only
    /// specified in the first message sent in a `StreamingSynthesize` call.
    indirect case streamingConfig(StreamingSynthesizeConfig?)
    /// Input to synthesize. Specified in all messages but the first in a
    /// `StreamingSynthesize` call.
    indirect case input(StreamingSynthesisInput?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.StreamingSynthesizeRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
