// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Provides configuration information for the StreamingSynthesize request.
public struct StreamingSynthesizeConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The desired voice of the synthesized audio.
  public var voice: VoiceSelectionParams? = nil

  /// Optional. The configuration of the synthesized audio.
  public var streamingAudioConfig: StreamingAudioConfig? = nil

  /// Optional. The pronunciation customizations are applied to the input. If
  /// this is set, the input is synthesized using the given pronunciation
  /// customizations.
  ///
  /// The initial support is for en-us, with plans to expand to other locales in
  /// the future. Instant Clone voices aren't supported.
  ///
  /// In order to customize the pronunciation of a phrase, there must be an exact
  /// match of the phrase in the input types. If using SSML, the phrase must not
  /// be inside a phoneme tag.
  public var customPronunciations: CustomPronunciations? = nil

  /// Optional. Advanced voice options.
  public var advancedVoiceOptions: AdvancedVoiceOptions? = nil

  /// Initialize a new instance of `StreamingSynthesizeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamingSynthesizeConfig().with { $0.voice = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.StreamingSynthesizeConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
