// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Input to be synthesized.
public struct StreamingSynthesisInput: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// This is system instruction supported only for controllable voice models.
  public var prompt: Swift.String? = nil

  public var inputSource: OneOf_InputSource? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `StreamingSynthesisInput`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamingSynthesisInput().with { $0.text = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let text = CodingKeys(stringValue: "text")
    static let markup = CodingKeys(stringValue: "markup")
    static let multiSpeakerMarkup = CodingKeys(stringValue: "multiSpeakerMarkup")
    static let prompt = CodingKeys(stringValue: "prompt")

    static let _knownKeys: Set<Swift.String> = [
      "text",
      "markup",
      "multiSpeakerMarkup",
      "prompt",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.prompt = try container.decodeIfPresent(Swift.String.self, forKey: .prompt)

    var inputSource: OneOf_InputSource? = nil
    let inputSourceCheckAndSet = {
      if inputSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'inputSource'"))
      }
      inputSource = $0
    }
    if let text = try container.decodeIfPresent(Swift.String.self, forKey: .text) {
      try inputSourceCheckAndSet(.text(text))
    }
    if let markup = try container.decodeIfPresent(Swift.String.self, forKey: .markup) {
      try inputSourceCheckAndSet(.markup(markup))
    }
    if let multiSpeakerMarkup = try container.decodeIfPresent(
      MultiSpeakerMarkup?.self, forKey: .multiSpeakerMarkup)
    {
      try inputSourceCheckAndSet(.multiSpeakerMarkup(multiSpeakerMarkup))
    }
    self.inputSource = inputSource
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.prompt, forKey: .prompt)

    if let choice = self.inputSource {
      switch choice {
      case .text(let value):
        try container.encode(value, forKey: .text)
      case .markup(let value):
        try container.encode(value, forKey: .markup)
      case .multiSpeakerMarkup(let value):
        try container.encode(value, forKey: .multiSpeakerMarkup)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_InputSource: Codable, Equatable, Sendable {
    /// The raw text to be synthesized. It is recommended that each input
    /// contains complete, terminating sentences, which results in better prosody
    /// in the output audio.
    case text(Swift.String)
    /// Markup for Chirp 3: HD voices specifically. This field may not be used
    /// with any other voices.
    case markup(Swift.String)
    /// Multi-speaker markup for Gemini TTS. This field may not
    /// be used with any other voices.
    indirect case multiSpeakerMarkup(MultiSpeakerMarkup?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.StreamingSynthesisInput"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
