// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Contains text input to be synthesized. Either `text` or `ssml` must be
/// supplied. Supplying both or neither returns
/// [google.rpc.Code.INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT]. The
/// input size is limited to 5000 bytes.
public struct SynthesisInput: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// This system instruction is supported only for controllable/promptable voice
  /// models. If this system instruction is used, we pass the unedited text to
  /// Gemini-TTS. Otherwise, a default system instruction is used. AI Studio
  /// calls this system instruction, Style Instructions.
  public var prompt: Swift.String? = nil

  /// Optional. The pronunciation customizations are applied to the input. If
  /// this is set, the input is synthesized using the given pronunciation
  /// customizations.
  ///
  /// The initial support is for en-us, with plans to expand to other locales in
  /// the future. Instant Clone voices aren't supported.
  ///
  /// In order to customize the pronunciation of a phrase, there must be an exact
  /// match of the phrase in the input types. If using SSML, the phrase must not
  /// be inside a phoneme tag.
  public var customPronunciations: CustomPronunciations? = nil

  /// The input source, which is either plain text or SSML.
  public var inputSource: OneOf_InputSource? = nil

  /// Initialize a new instance of `SynthesisInput`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SynthesisInput().with { $0.text = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case text = "text"
    case markup = "markup"
    case ssml = "ssml"
    case multiSpeakerMarkup = "multiSpeakerMarkup"
    case prompt = "prompt"
    case customPronunciations = "customPronunciations"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.prompt = try container.decodeIfPresent(Swift.String.self, forKey: .prompt)
    self.customPronunciations = try container.decodeIfPresent(
      CustomPronunciations.self, forKey: .customPronunciations)

    var inputSource: OneOf_InputSource? = nil
    let inputSourceCheckAndSet = {
      if inputSource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'inputSource'"))
      }
      inputSource = $0
    }
    if let text = try container.decodeIfPresent(Swift.String.self, forKey: .text) {
      try inputSourceCheckAndSet(.text(text))
    }
    if let markup = try container.decodeIfPresent(Swift.String.self, forKey: .markup) {
      try inputSourceCheckAndSet(.markup(markup))
    }
    if let ssml = try container.decodeIfPresent(Swift.String.self, forKey: .ssml) {
      try inputSourceCheckAndSet(.ssml(ssml))
    }
    if let multiSpeakerMarkup = try container.decodeIfPresent(
      MultiSpeakerMarkup?.self, forKey: .multiSpeakerMarkup)
    {
      try inputSourceCheckAndSet(.multiSpeakerMarkup(multiSpeakerMarkup))
    }
    self.inputSource = inputSource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.prompt, forKey: .prompt)
    try container.encode(self.customPronunciations, forKey: .customPronunciations)

    if let choice = self.inputSource {
      switch choice {
      case .text(let value):
        try container.encode(value, forKey: .text)
      case .markup(let value):
        try container.encode(value, forKey: .markup)
      case .ssml(let value):
        try container.encode(value, forKey: .ssml)
      case .multiSpeakerMarkup(let value):
        try container.encode(value, forKey: .multiSpeakerMarkup)
      }
    }
  }

  /// The input source, which is either plain text or SSML.
  public enum OneOf_InputSource: Codable, Equatable, Sendable {
    /// The raw text to be synthesized.
    case text(Swift.String)
    /// Markup for Chirp 3: HD voices specifically. This field may not be used
    /// with any other voices.
    case markup(Swift.String)
    /// The SSML document to be synthesized. The SSML document must be valid
    /// and well-formed. Otherwise the RPC will fail and return
    /// [google.rpc.Code.INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT]. For
    /// more information, see
    /// [SSML](https://cloud.google.com/text-to-speech/docs/ssml).
    case ssml(Swift.String)
    /// The multi-speaker input to be synthesized. Only applicable for
    /// multi-speaker synthesis.
    indirect case multiSpeakerMarkup(MultiSpeakerMarkup?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.SynthesisInput"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
