// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The top-level message sent by the client for the
/// `SynthesizeLongAudio` method.
public struct SynthesizeLongAudioRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource states of the request in the form of
  /// `projects/*/locations/*`.
  public var parent: Swift.String = Swift.String()

  /// Required. The Synthesizer requires either plain text or SSML as input.
  public var input: SynthesisInput? = nil

  /// Required. The configuration of the synthesized audio.
  public var audioConfig: AudioConfig? = nil

  /// Required. Specifies a Cloud Storage URI for the synthesis results. Must be
  /// specified in the format: `gs://bucket_name/object_name`, and the bucket
  /// must already exist.
  public var outputGcsUri: Swift.String = Swift.String()

  /// Required. The desired voice of the synthesized audio.
  public var voice: VoiceSelectionParams? = nil

  /// Initialize a new instance of `SynthesizeLongAudioRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SynthesizeLongAudioRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.SynthesizeLongAudioRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
