// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The top-level message sent by the client for the
/// `SynthesizeLongAudio` method.
public struct SynthesizeLongAudioRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource states of the request in the form of
  /// `projects/*/locations/*`.
  public var parent: Swift.String = Swift.String()

  /// Required. The Synthesizer requires either plain text or SSML as input.
  public var input: SynthesisInput? = nil

  /// Required. The configuration of the synthesized audio.
  public var audioConfig: AudioConfig? = nil

  /// Required. Specifies a Cloud Storage URI for the synthesis results. Must be
  /// specified in the format: `gs://bucket_name/object_name`, and the bucket
  /// must already exist.
  public var outputGcsUri: Swift.String = Swift.String()

  /// Required. The desired voice of the synthesized audio.
  public var voice: VoiceSelectionParams? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SynthesizeLongAudioRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SynthesizeLongAudioRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let input = CodingKeys(stringValue: "input")
    static let audioConfig = CodingKeys(stringValue: "audioConfig")
    static let outputGcsUri = CodingKeys(stringValue: "outputGcsUri")
    static let voice = CodingKeys(stringValue: "voice")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "input",
      "audioConfig",
      "outputGcsUri",
      "voice",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.input = try container.decodeIfPresent(SynthesisInput.self, forKey: .input)
    self.audioConfig = try container.decodeIfPresent(AudioConfig.self, forKey: .audioConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputGcsUri) {
      self.outputGcsUri = value
    }
    self.voice = try container.decodeIfPresent(VoiceSelectionParams.self, forKey: .voice)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.input, forKey: .input)
    try container.encodeIfPresent(self.audioConfig, forKey: .audioConfig)
    try container.encode(self.outputGcsUri, forKey: .outputGcsUri)
    try container.encodeIfPresent(self.voice, forKey: .voice)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.SynthesizeLongAudioRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
