// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class TextToSpeechLogging: TextToSpeechStub {
    let inner: any TextToSpeechStub
    let logger: Logger

    public init(_ inner: any TextToSpeechStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-texttospeech-v1"
      logger[metadataKey: "gcp.client.service"] = "texttospeech"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TextToSpeech"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listVoices(
      request: ListVoicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTexttospeechV1.ListVoicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVoices",
        action: {
          (r: ListVoicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTexttospeechV1.ListVoicesResponse
          in
          return try await self.inner.listVoices(request: r, options: o)
        })
    }

    public func synthesizeSpeech(
      request: SynthesizeSpeechRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTexttospeechV1.SynthesizeSpeechResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "synthesizeSpeech",
        action: {
          (r: SynthesizeSpeechRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTexttospeechV1.SynthesizeSpeechResponse
          in
          return try await self.inner.synthesizeSpeech(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongrunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
