// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service that implements Google Cloud Text-to-Speech API.
///
/// @Snippet(path: "TextToSpeechQuickstart")
public final class TextToSpeechClient: Clients.TextToSpeechProtocol, Sendable {
  let inner: any Clients.TextToSpeechStub

  /// Creates a new `TextToSpeechClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.TextToSpeechStub = try Clients.TextToSpeechTransport(options)
    inner = Clients.TextToSpeechRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TextToSpeechLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Returns a list of Voice supported for synthesis.
  ///
  /// @Snippet(path: "TextToSpeech_ListVoices")
  public func listVoices(
    request: ListVoicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTextToSpeechV1.ListVoicesResponse {
    try await self.inner.listVoices(request: request, options: options)
  }

  /// Synthesizes speech synchronously: receive results after all text input
  /// has been processed.
  ///
  /// @Snippet(path: "TextToSpeech_SynthesizeSpeech")
  public func synthesizeSpeech(
    request: SynthesizeSpeechRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTextToSpeechV1.SynthesizeSpeechResponse {
    try await self.inner.synthesizeSpeech(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TextToSpeech_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TextToSpeech_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TextToSpeechClient`.
  ///
  /// To mock `TextToSpeechClient` change your functions to receive
  /// `some TextToSpeechProtocol` or `any TextToSpeechProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TextToSpeechProtocol: Sendable {
    /// See `TextToSpeechClient.listVoices`.
    func listVoices(
      request: ListVoicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTextToSpeechV1.ListVoicesResponse

    /// See `TextToSpeechClient.synthesizeSpeech`.
    func synthesizeSpeech(
      request: SynthesizeSpeechRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTextToSpeechV1.SynthesizeSpeechResponse

    /// See `TextToSpeechClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.TextToSpeechProtocol {
  public func listVoices(request: ListVoicesRequest) async throws
    -> GoogleCloudTextToSpeechV1.ListVoicesResponse
  {
    try await self.listVoices(request: request, options: .init())
  }

  public func listVoices(
    request: ListVoicesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTextToSpeechV1.ListVoicesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listVoices(
    languageCode: Swift.String,
  ) async throws -> GoogleCloudTextToSpeechV1.ListVoicesResponse {
    let request = ListVoicesRequest().with {
      $0.languageCode = languageCode
    }
    return try await self.listVoices(request: request)
  }

  public func synthesizeSpeech(request: SynthesizeSpeechRequest) async throws
    -> GoogleCloudTextToSpeechV1.SynthesizeSpeechResponse
  {
    try await self.synthesizeSpeech(request: request, options: .init())
  }

  public func synthesizeSpeech(
    request: SynthesizeSpeechRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudTextToSpeechV1.SynthesizeSpeechResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func synthesizeSpeech(
    input: SynthesisInput?,
    voice: VoiceSelectionParams?,
    audioConfig: AudioConfig?,
  ) async throws -> GoogleCloudTextToSpeechV1.SynthesizeSpeechResponse {
    let request = SynthesizeSpeechRequest().with {
      $0.input = input
      $0.voice = voice
      $0.audioConfig = audioConfig
    }
    return try await self.synthesizeSpeech(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TextToSpeech_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
