// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service that implements Google Cloud Text-to-Speech API.
///
/// @Snippet(path: "TextToSpeechLongAudioSynthesizeQuickstart")
public final class TextToSpeechLongAudioSynthesizeClient: Clients
    .TextToSpeechLongAudioSynthesizeProtocol, Sendable
{
  let inner: any Clients.TextToSpeechLongAudioSynthesizeStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `TextToSpeechLongAudioSynthesizeClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.TextToSpeechLongAudioSynthesizeStub =
      try Clients.TextToSpeechLongAudioSynthesizeTransport(options)
    inner = Clients.TextToSpeechLongAudioSynthesizeRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TextToSpeechLongAudioSynthesizeLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Synthesizes long form text asynchronously.
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_SynthesizeLongAudio")
  public func synthesizeLongAudio(
    request: SynthesizeLongAudioRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.synthesizeLongAudio(request: request, options: options)
  }

  /// Synthesizes long form text asynchronously.
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_SynthesizeLongAudio")
  public func synthesizeLongAudioPollingUntilDone(
    request: SynthesizeLongAudioRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<SynthesizeLongAudioResponse> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<SynthesizeLongAudioResponse>.State in
      return try op._extractStatus(SynthesizeLongAudioResponse.self)
    }
    let rawOp = try await self.synthesizeLongAudio(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws
        -> GoogleGax._PollableOperationImpl<SynthesizeLongAudioResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TextToSpeechLongAudioSynthesizeClient`.
  ///
  /// To mock `TextToSpeechLongAudioSynthesizeClient` change your functions to receive
  /// `some TextToSpeechLongAudioSynthesizeProtocol` or `any TextToSpeechLongAudioSynthesizeProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TextToSpeechLongAudioSynthesizeProtocol: Sendable {
    /// See `TextToSpeechLongAudioSynthesizeClient.synthesizeLongAudio`.
    func synthesizeLongAudio(
      request: SynthesizeLongAudioRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TextToSpeechLongAudioSynthesizeClient.synthesizeLongAudio`.
    func synthesizeLongAudioPollingUntilDone(
      request: SynthesizeLongAudioRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<SynthesizeLongAudioResponse>

    /// See `TextToSpeechLongAudioSynthesizeClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.TextToSpeechLongAudioSynthesizeProtocol {
  public func synthesizeLongAudio(request: SynthesizeLongAudioRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.synthesizeLongAudio(request: request, options: .init())
  }

  public func synthesizeLongAudio(
    request: SynthesizeLongAudioRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func synthesizeLongAudioPollingUntilDone(request: SynthesizeLongAudioRequest) async throws
    -> any GoogleGax.PollableOperation<SynthesizeLongAudioResponse>
  {
    try await self.synthesizeLongAudioPollingUntilDone(request: request, options: .init())
  }

  public func synthesizeLongAudioPollingUntilDone(
    request: SynthesizeLongAudioRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<SynthesizeLongAudioResponse> {
    let poll = {
      @Sendable () async throws
        -> GoogleGax._PollableOperationImpl<SynthesizeLongAudioResponse>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
