// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service that implements Google Cloud Text-to-Speech API.
///
/// @Snippet(path: "TextToSpeechLongAudioSynthesizeQuickstart")
public class TextToSpeechLongAudioSynthesizeClient: Clients.TextToSpeechLongAudioSynthesizeProtocol
{
  let inner: any Clients.TextToSpeechLongAudioSynthesizeStub

  /// Creates a new `TextToSpeechLongAudioSynthesizeClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.TextToSpeechLongAudioSynthesizeStub =
      try Clients.TextToSpeechLongAudioSynthesizeTransport(options)
    inner = Clients.TextToSpeechLongAudioSynthesizeRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TextToSpeechLongAudioSynthesizeLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Synthesizes long form text asynchronously.
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_SynthesizeLongAudio")
  public func synthesizeLongAudio(
    request: SynthesizeLongAudioRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.synthesizeLongAudio(request: request, options: options)
  }

  /// Synthesizes long form text asynchronously.
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_SynthesizeLongAudio")
  public func synthesizeLongAudio(
    withPolling: SynthesizeLongAudioRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<SynthesizeLongAudioResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<SynthesizeLongAudioResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try SynthesizeLongAudioResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.synthesizeLongAudio(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<SynthesizeLongAudioResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "TextToSpeechLongAudioSynthesize_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TextToSpeechLongAudioSynthesizeClient`.
  ///
  /// To mock `TextToSpeechLongAudioSynthesizeClient` change your functions to receive
  /// `some TextToSpeechLongAudioSynthesizeProtocol` or `any TextToSpeechLongAudioSynthesizeProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TextToSpeechLongAudioSynthesizeProtocol {
    /// See `TextToSpeechLongAudioSynthesizeClient.synthesizeLongAudio`.
    func synthesizeLongAudio(request: SynthesizeLongAudioRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `TextToSpeechLongAudioSynthesizeClient.synthesizeLongAudio`.
    func synthesizeLongAudio(withPolling: SynthesizeLongAudioRequest) async throws
      -> any GoogleCloudGax.PollableOperation<SynthesizeLongAudioResponse>

    /// See `TextToSpeechLongAudioSynthesizeClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `TextToSpeechLongAudioSynthesizeClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `TextToSpeechLongAudioSynthesizeClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `TextToSpeechLongAudioSynthesizeClient.synthesizeLongAudio`.
    func synthesizeLongAudio(
      request: SynthesizeLongAudioRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `TextToSpeechLongAudioSynthesizeClient.synthesizeLongAudio`.
    func synthesizeLongAudio(
      withPolling: SynthesizeLongAudioRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<SynthesizeLongAudioResponse>

    /// See `TextToSpeechLongAudioSynthesizeClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `TextToSpeechLongAudioSynthesizeClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>
  }
}

// Default implementations
extension Clients.TextToSpeechLongAudioSynthesizeProtocol {
  public func synthesizeLongAudio(request: SynthesizeLongAudioRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.synthesizeLongAudio(request: request, options: .init())
  }

  public func synthesizeLongAudio(
    request: SynthesizeLongAudioRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func synthesizeLongAudio(withPolling: SynthesizeLongAudioRequest) async throws
    -> any GoogleCloudGax.PollableOperation<SynthesizeLongAudioResponse>
  {
    try await self.synthesizeLongAudio(withPolling: withPolling, options: .init())
  }

  public func synthesizeLongAudio(
    withPolling: SynthesizeLongAudioRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<SynthesizeLongAudioResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<SynthesizeLongAudioResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
