// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Description of which voice to use for a synthesis request.
public struct VoiceSelectionParams: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The language (and potentially also the region) of the voice
  /// expressed as a [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt)
  /// language tag, e.g. "en-US". This should not include a script tag (e.g. use
  /// "cmn-cn" rather than "cmn-Hant-cn"), because the script will be inferred
  /// from the input provided in the SynthesisInput.  The TTS service
  /// will use this parameter to help choose an appropriate voice.  Note that
  /// the TTS service may choose a voice with a slightly different language code
  /// than the one selected; it may substitute a different region
  /// (e.g. using en-US rather than en-CA if there isn't a Canadian voice
  /// available), or even a different language, e.g. using "nb" (Norwegian
  /// Bokmal) instead of "no" (Norwegian)".
  public var languageCode: Swift.String = Swift.String()

  /// The name of the voice. If both the name and the gender are not set,
  /// the service will choose a voice based on the other parameters such as
  /// language_code.
  public var name: Swift.String = Swift.String()

  /// The preferred gender of the voice. If not set, the service will
  /// choose a voice based on the other parameters such as language_code and
  /// name. Note that this is only a preference, not requirement; if a
  /// voice of the appropriate gender is not available, the synthesizer should
  /// substitute a voice with a different gender rather than failing the request.
  public var ssmlGender: SsmlVoiceGender = SsmlVoiceGender()

  /// The configuration for a custom voice. If [CustomVoiceParams.model] is set,
  /// the service will choose the custom voice matching the specified
  /// configuration.
  public var customVoice: CustomVoiceParams? = nil

  /// Optional. The configuration for a voice clone. If
  /// [VoiceCloneParams.voice_clone_key] is set, the service chooses the voice
  /// clone matching the specified configuration.
  public var voiceClone: VoiceCloneParams? = nil

  /// Optional. The name of the model. If set, the service will choose the model
  /// matching the specified configuration.
  public var modelName: Swift.String = Swift.String()

  /// Optional. The configuration for a Gemini multi-speaker text-to-speech
  /// setup. Enables the use of two distinct voices in a single synthesis
  /// request.
  public var multiSpeakerVoiceConfig: MultiSpeakerVoiceConfig? = nil

  /// Initialize a new instance of `VoiceSelectionParams`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VoiceSelectionParams().with { $0.languageCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.VoiceSelectionParams"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
