// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Description of a voice supported by the TTS service.
public struct Voice: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The languages that this voice supports, expressed as
  /// [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language tags (e.g.
  /// "en-US", "es-419", "cmn-tw").
  public var languageCodes: [Swift.String] = []

  /// The name of this voice.  Each distinct voice has a unique name.
  public var name: Swift.String = Swift.String()

  /// The gender of this voice.
  public var ssmlGender: SsmlVoiceGender = SsmlVoiceGender()

  /// The natural sample rate (in hertz) for this voice.
  public var naturalSampleRateHertz: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Voice`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Voice().with { $0.languageCodes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let languageCodes = CodingKeys(stringValue: "languageCodes")
    static let name = CodingKeys(stringValue: "name")
    static let ssmlGender = CodingKeys(stringValue: "ssmlGender")
    static let naturalSampleRateHertz = CodingKeys(stringValue: "naturalSampleRateHertz")

    static let _knownKeys: Set<Swift.String> = [
      "languageCodes",
      "name",
      "ssmlGender",
      "naturalSampleRateHertz",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .languageCodes) {
      self.languageCodes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(SsmlVoiceGender.self, forKey: .ssmlGender) {
      self.ssmlGender = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .naturalSampleRateHertz)
    {
      self.naturalSampleRateHertz = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.languageCodes, forKey: .languageCodes)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.ssmlGender, forKey: .ssmlGender)
    try container.encode(self.naturalSampleRateHertz, forKey: .naturalSampleRateHertz)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.texttospeech.v1.Voice"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
